### ISSUE TITLE
[ADD EXAMPLE] Pythagoras tree

### ISSUE THREAD

**Issue by jeremydouglass** [jeremydouglass/rosetta_examples_p5#29]
### URL of task
https://rosettacode.org/wiki/Pythagoras_tree#Processing

### Next steps
Create and submit a fully commented Processing sketch based on the linked example -- either as an issue comment or as a pull request. See CONTRIBUTING.md for details.

**Comment by da8** [comment]
I am working on that example.

**Comment by jeremydouglass** [comment]
Closed by #39
