### ISSUE TITLE
[ADD EXAMPLE] Draw A Clock

### ISSUE THREAD

**Issue by villares** [jeremydouglass/rosetta_examples_p5#49]
**Instructions:**
### URL of task
http://rosettacode.org/wiki/Draw_a_clock#Processing

### Next steps
- [X] I requesting that somebody else write the .pde AND .pyde sketch (both are there...)

**Comment by jeremydouglass** [comment]
Hey viillares -- should I close this?

pde: 7baf9b6
<strike> pyde: 46291cf </strike>

Oops! pyde is on the wiki, not yet in the Python examples. Got it.

**Comment by villares** [comment]
For some reason I missed the .pde version!

**Comment by jeremydouglass** [comment]
Closed by d3c1cc6e
